# Generated by Django 5.2.6 on 2025-09-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bitrhday',
            field=models.DateField(default='1999-06-02', verbose_name='Биография'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='hello_autho_surname_eaffdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('surname', 'bio'), name='unique_surname_bio'),
        ),
    ]
