# Generated by Django 5.2.7 on 2025-10-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_author_options_alter_author_bitrhday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('data', models.CharField(max_length=255, verbose_name='Данные')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('data', models.CharField(max_length=255, verbose_name='Данные')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(verbose_name='Время отправки')),
                ('Chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.chat')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['sending_time'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('validity_period', models.DateField(verbose_name='Срок истечения')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_publisher',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['validity_period'], name='hello_subsc_validit_a3d370_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['price'], name='hello_subsc_price_607954_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['title'], name='hello_subsc_title_8ecb59_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.subscription'),
        ),
        migrations.AddField(
            model_name='message',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.user'),
        ),
        migrations.AddField(
            model_name='channel',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.user'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='hello_user_usernam_c61bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='hello_user_phone_n_11067e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='hello_user_email_e437bc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sending_time'], name='hello_messa_sending_4e41d8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['Chat_id'], name='hello_messa_Chat_id_fbba54_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['User_id'], name='hello_messa_User_id_3c554a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['name'], name='hello_chat_name_10431f_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['name'], name='hello_chann_name_39b2c0_idx'),
        ),
    ]
