# Generated by Django 5.2.6 on 2025-11-27 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], default='basic', max_length=50, verbose_name='Тип подписки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('validity_period', models.DateField(verbose_name='Срок истечения')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['price'], name='halo_subscr_price_2a8ea9_idx'), models.Index(fields=['title'], name='halo_subscr_title_287cf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='halo.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('sending_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='halo.user')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-sending_time'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('name', models.CharField(max_length=50, verbose_name='Название чата')),
                ('messages', models.ManyToManyField(blank=True, related_name='chat_messages', to='halo.message')),
                ('users', models.ManyToManyField(related_name='user_chats', to='halo.user')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('name', models.CharField(max_length=50, verbose_name='Название канала')),
                ('messages', models.ManyToManyField(blank=True, related_name='channel_messages', to='halo.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channels', to='halo.user')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='halo_user_usernam_82ec71_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['text'], name='halo_messag_text_81b95e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sending_time'], name='halo_messag_sending_f946e3_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['name'], name='halo_chat_name_8c8209_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['name'], name='halo_channe_name_015759_idx'),
        ),
    ]
